model:
# TODO
  code_size: 4
  window: 4
  window_1: 4
  window_2: 4
  
learning:
  batch_size: 
  lr: 
  epochs: 40
  decay_steps: 
  grad_clip: 0. # no clipping
  accelerator: cuda
  devices: 1

loss:
  temperature: 0.1

predictions:
  scale: 1.
  step: 1
  alpha: 1.

early_stopping:
  monitor: train_loss_epoch
  min_delta: 0.0001
  patience: 5

cusum:
  normal_sigma: null
  cp_sigma: null
  half_window: 1

distance:
  window_size_list: [1, 2, 3]
  anchor_window_type_list: ["start", "prev"]

evaluation:
  margin_list: [1, 2, 4]

model_type: ts2vec